%% Exact linearization of the Simulink model single_motor_sl
%
% This MATLAB script is the command line equivalent of the exact
% linearization tab in linear analysis tool with current settings.
% It produces the exact same linearization results as hitting the Linearize button.

% MATLAB(R) file generated by MATLAB(R) 9.8 and Simulink Control Design (TM) 5.5.
%
% Generated on: 06-Sep-2020 09:23:56

%% Specify the model name
model = 'single_motor_sl';
load_system(model);
open_system(model);
% port:  linio(model/block, port number on block, type (in or out m.fl))
ios(1) = linio('single_motor_sl/trust_step',1,'openinput');
ios(2) = linio('single_motor_sl/hardware',2,'openoutput');
setlinio(model,ios);
%%
%io = getlinio(model);
% Specify the operating point
% Use the snapshot times
op = 4;
% Linearize the model
sys = linearize(model,ios,op);
% get transfer function
[num,den] = ss2tf(sys.A, sys.B, sys.C, sys.D)
G = tf(num, den)

